/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;


import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.tree.TreeModel;
import negocio.Activo;
import negocio.Archivos;
import negocio.Empresa;
import negocio.TipoActivo;

/**
 * @author Carlos Manrique
 * @author Alfredo Santamaria
 * @author Laura Chacón
 */
public class AgregarActivo extends javax.swing.JFrame {

    /**
     * arbol que construlle los tipos del activo
     */
    private GenealogyTree genealogyTree;
    /**
     * empresa actual
     */
    private Empresa empresa;
    /**
     * nuevo activo a agregar
     */
    private Activo nuevoActivo;
    /**
     * ventana padre
     */
    private JFrame parent;
    
    /**
     * Creates new form ActivosEmpresa
     * @param e empresa actual
     * @param parent ventana padre
     */
    public AgregarActivo(Empresa e, JFrame parent) {
        this.empresa = e;
        nuevoActivo = new Activo();
        this.parent = parent;
        initComponents();        
    }

    AgregarActivo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * retrorna la enumeracion TipoActivo raiz
     * @return TipoActivo raiz
     */
     public TipoActivo getGenealogyGraph() {
        return TipoActivo.Tipo;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genealogyTree = new GenealogyTree(getGenealogyGraph());
        tiposJSP = new javax.swing.JScrollPane(genealogyTree);
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nombreActivoJTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTiposJL = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar Activo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Activo:");

        jButton2.setText("Agregar tipo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        nombreActivoJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActivoJTFActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipos Activo:");

        jScrollPane1.setViewportView(listaTiposJL);

        jButton3.setText("Quitar Tipo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(40, 40, 40)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(tiposJSP, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(jButton2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreActivoJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreActivoJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(tiposJSP))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActivoJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActivoJTFActionPerformed

    }//GEN-LAST:event_nombreActivoJTFActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        TreeModel treeModel = genealogyTree.getModel();
        TipoActivo ta = (TipoActivo)genealogyTree.getLastSelectedPathComponent();
        nuevoActivo.addTipo(ta);
        loadListaTipos();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        ListModel listmodel = listaTiposJL.getModel();
        int index = listaTiposJL.getSelectedIndex();
        if(index == -1) return;
        String tipoSelected = (String) listmodel.getElementAt(index);
        
        for (Iterator<TipoActivo> it = nuevoActivo.getTipos().iterator(); it.hasNext(); ){
            TipoActivo ta = it.next();
            if( ta.toString().equals(tipoSelected) ){
                it.remove();
            }
        }
        loadListaTipos();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        boolean correct = true;
        if(nombreActivoJTF.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese el nombre del activo", "Error", JOptionPane.ERROR_MESSAGE);
            correct = false;
        }                JOptionPane.showMessageDialog(this, "El nombre del activo ya existe", "Error", JOptionPane.ERROR_MESSAGE);

        for(Activo a : empresa.getActivos()){
            if(a.getNombre().equals(nombreActivoJTF.getText())){
                correct = false;
                break;
            }
        }
        if(correct){
            nuevoActivo.setNombre(nombreActivoJTF.getText());
            empresa.addActivo(nuevoActivo);
            ((ActivosEmpresa)parent).loadActivos();
            Archivos.guardarArchivo();
            this.dispose();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * recarga la lista de tipos que se seleccionan
     * para el nuevo activo
     */
    private void loadListaTipos(){
        Object[] obs = new Object[nuevoActivo.getTipos().size()];
        int i = 0;
        for(TipoActivo ta : nuevoActivo.getTipos()){
             obs[i++] = ta.toString();
        }
        listaTiposJL.setListData(obs);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaTiposJL;
    private javax.swing.JTextField nombreActivoJTF;
    private javax.swing.JScrollPane tiposJSP;
    // End of variables declaration//GEN-END:variables
}
